language: node_js
node_js:
- "10"
cache:
  yarn: true
  directories:
  - node_modules
install:
  - yarn install
script:
  - yarn build
after_script:
  script:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  - yarn publish --new-version patch
  on:
    branch: master