language: node_js
node_js:
- "10"
cache:
  yarn: true
  directories:
  - node_modules
install:
  - yarn install
  - yarn build
deploy:
  provider: npm
  email: support@xy.company
  api_key: $NPM_TOKEN
  on:
    branch: master