language: node_js
node_js:
- "10"
cache:
  yarn: true
  directories:
  - node_modules
install:
  - yarn install
  - yarn build
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
deploy:
  provider: script
  skip_cleanup: true
  script: npm version patch && npm publish
  on:
    branch: master